Repository osbuild/cockpit-composer, pull requests merged in 2020-10, with the labels that each got.

#1117 package.json: Update @patternfly/react-table package dependency
  package.json
Labels: bot

#1119 Update translations from Fedora Weblate
  po/ja.po
Labels: bot

#1122 package.json: Update @patternfly/patternfly package dependency
  package.json
Labels: bot

#1118 test: Use the @noretry decorator for check-image
  Makefile
  test/verify/check-image
Labels: blocked

#1131 Run po-refresh and npm-update in GitHub workflows
  .github/workflows/npm-update.yml
  .github/workflows/po-refresh.yml
  .tasks
  README.md
Labels: no-test

#1124 package.json: Update @patternfly/react-icons package dependency
  package.json
Labels: bot

#1127 package.json: Update react package dependency
  package.json
Labels: bot
